blank_issues_enabled: false
contact_links:
  - name: ğŸ“¢ Feedback
    about: Have an idea for a new feature? Open a discussion and let's talk about it!
    url: https://github.com/puppetlabs/prm/discussions/new
  - name: â” Ask a question about Puppet Runtime Manager
    about: Please check out the community forum for discussions about the Puppet Runtime Manager.
    url: https://github.com/puppetlabs/prm/discussions/new
